parameters:
  - name: azureSubscription
    type: string
  - name: resourceGroupName
    type: string
  - name: appName
    type: string
  - name: environmentName
    type: string

stages:
- stage: Application
jobs:
  - deployment: dev
    displayName: 'Deploy Todo API to $(environmentName)'
    environment: $(environmentName)-$(appName)
    workspace:
      clean: all
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 15
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps: 
            - task: DownloadBuildArtifacts@1
              displayName: 'copy build artifacts'
              inputs:
                artifactName: 'drop'
                buildVersionToDownload: latest

            - task: AzureFunctionApp@1
              inputs:
                azureSubscription: $(azureSubscription)
                resourceGroupName: $(resourceGroupName)
                appType: functionAppLinux
                appName: $(appName)
                package: $(System.ArtifactsDirectory)/**/*.zip
        