parameters:
  - name: azureSubscription
    type: string
  - name: resourceGroupName
    type: string
  - name: appName
    type: string
  - name: environmentName
    type: string
  - name: location
    type: string
    default: 'australiaeast'
  - name: deploymentName
    type: string
    default: 'infra-deployment'
  - name: templateFileName
    type: string
    default: 'main.bicep'

jobs:
- deployment: "${{ parameters.environmentName }}_${{ parameters.appName }}_infra"
  displayName: 'Deploy intrastructure to $(environmentName)'
  environment: ${{ parameters.environmentName }}-${{ parameters.appName }}
  workspace:
    clean: all
  timeoutInMinutes: 10
  cancelTimeoutInMinutes: 15
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps: 
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'bicep'

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}

                az deployment group create \
                  --name ${{ parameters.deploymentName }} \
                  --resource-group ${{ parameters.resourceGroupName }} \
                  --template-file ${{ parameters.templateFileName }} \
                  --parameters appName=${{ parameters.appName }} \
                  --parameters location=${{ parameters.location }} \
                  --parameters environmentName=${{ parameters.environmentName }}
