trigger:
- main

name: 'todo-api build & deployment'

variables:
  azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  appName: 'todoapi'

stages:
- template: templates/build.yaml

- stage: 'dev_infra'
  displayName: 'Dev Infra Deployment'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: dev

- stage: 'dev_deploy'
  displayName: 'Dev Function Deployment'
  variables: 
    - name: funcAppName
      value: $[ stageDependencies.dev_infra.infra.outputs['bicep.funcName'] ]
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: ${{ variables.funcAppName }}
        environmentName: dev

- stage: 'prod_infra'
  displayName: 'Prod Infra Deployment'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: prod
    
- stage: 'prod_deploy'
  displayName: 'Prod Function Deployment'  
  variables: 
    - name: funcAppName
      value: $[ stageDependencies.prod_infra.infra.outputs['bicep.funcName'] ]
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: ${{ variables.funcAppName }}
        environmentName: prod
        
    