trigger:
- main

name: 'todo-api build & deployment'

variables:
  azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  appName: 'todoapi'

stages:
- template: templates/build.yaml

- stage: 'dev_infra'
  displayName: 'Dev Infrastructure'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: dev

- stage: 'dev_deploy'
  displayName: 'Dev Function Deployment'
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: ${{ dependencies.dev_infra.outputs['deploy.outputVars.funcName'] }}
        environmentName: dev

- stage: 'prod_infra'
  displayName: 'Prod Infrastructure'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: prod
    
- stage: 'prod_deploy'
  displayName: 'Prod Function Deployment'  
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: ${{ dependencies.prod_infra.outputs['deploy.outputVars.funcName'] }}
        environmentName: prod
        
    