trigger:
- main

name: 'todo-api build & deployment'

variables:
  azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  appName: 'todoapi'

stages:
- template: templates/build.yaml

- stage: 'dev_infra'
  displayName: 'Deploy Dev Infra'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: dev

- stage: 'dev_deploy'
  dependsOn: 'dev_infra'
  displayName: 'Deploy Dev Function'
  variables:
    funcName: $[stageDependencies.dev_infra.infra.outputs['infra.bicep.funcName']]
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: clj5m4jabpga6-dev-todoapi #${{ variables.funcName }}
        environmentName: dev

- stage: 'prod_infra'
  displayName: 'Deploy Prod Infra'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: prod
    
- stage: 'prod_deploy'
  dependsOn: 'prod_infra'
  displayName: 'Deploy Prod Function'  
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: yjr53qywj6aoc-prod-todoapi #$[stageDependencies.prod_infra.infra.outputs['infra.bicep.funcName']]
        environmentName: prod
        