trigger:
- main

name: 'todo-api build & deployment'

variables:
  azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  appName: 'todoapi'

stages:
- template: templates/build.yaml

- stage: 'dev_infra'
  displayName: 'Deploy Dev Infra'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: dev

- stage: 'dev_deploy'
  displayName: 'Deploy Dev Function'
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "dev-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: "$[ stageDependencies.dev_infra.infra.outputs['bicep.funcName'] ]"
        environmentName: dev

- stage: 'prod_infra'
  displayName: 'Deploy Prod Infra'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        environmentName: prod
    
- stage: 'prod_deploy'
  displayName: 'Deploy Prod Function'  
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: ${{ variables.azureSubscription }}
        resourceGroupName: "prod-${{ variables.appName }}-rg"
        appName: ${{ variables.appName }}
        functionAppName: "$[ stageDependencies.prod_infra.infra.outputs['bicep.funcName'] ]"
        environmentName: prod
        
    