trigger:
- main

name: 'todo-api build & deployment'

variables:
  azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  appName: 'todo-api'

stages:
- template: templates/build.yaml

- stage: 'dev_infra'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: azureSubscription
        resourceGroupName: "dev-${{ variables['appName'] }}-rg"
        appName: variables['appName']
        environmentName: dev

- stage: 'dev_deploy'
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: azureSubscription
        resourceGroupName: "dev-${{ variables['appName'] }}-rg"
        appName: variables['appName']
        environmentName: dev

- stage: 'prod_infra'
  jobs:
    - template: templates/infra.yaml
      parameters:
        azureSubscription: azureSubscription
        resourceGroupName: "prod-${{ variables['appName'] }}-rg"
        appName: variables['appName']
        environmentName: prod
    
- stage: 'prod_deploy'
  jobs:
    - template: templates/deploy.yaml
      parameters:
        azureSubscription: azureSubscription
        resourceGroupName: "prod-${{ variables['appName'] }}-rg"
        appName: variables['appName']
        environmentName: prod
        
    