trigger:
- main

name: 'todo-api build & deployment'

variables:
  azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  appName: 'todo-api'
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'build'
    displayName: 'Build application'
    pool: 
      vmImage: $(vmImage)
    jobs:
      - job: 'build'
      -  template: templates/build.yaml
  
  - stage: 'infra'
    displayName: 'Deploy Infrastructure'
    pool:
      vmImage: $(vmImage)
    jobs:
      - template: templates/infra.yaml
        parameters:
          azureSubscription: azureSubscription
          resourceGroupName: dev-$(appName)-rg
          appName: dev-$(appName)
          environmentName: dev

      - template: templates/deploy.yaml
        parameters:
          azureSubscription: azureSubscription
          resourceGroupName: dev-$(appName)-rg
          appName: dev-$(appName)
          environmentName: dev

      - template: templates/infra.yaml
        parameters:
          azureSubscription: azureSubscription
          resourceGroupName: prod-$(appName)-rg
          appName: prod-$(appName)
          environmentName: prod
          
      - template: templates/deploy.yaml
        parameters:
          azureSubscription: azureSubscription
          resourceGroupName: prod-$(appName)-rg
          appName: prod-$(appName)
          environmentName: prod
          
          